##################################################################
# Pure-vagrant Vagrant + Docker Vagrantfile
# DOCKER with multiple containers
# REQUIRES:  Vagrant 1.7.2+ VirtualBox 4.3.14+
# Uses Vagrantfiles for defining and launching docker containers
##################################################################

# Placing container with DB first to avoid vagrant parallel issues
# Start using vagrant up --provision-with docker --no-parallel

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#Define container 1
config.vm.define "postgres" do |v|
  v.vm.provider "docker" do |d|
    d.image = "library/postgres"
    d.volumes = ["/var/docker/postgres:/data"]
    d.ports = ["5432:5432"]
    d.env = {
      USER: "mydbuser",
      PASS: "mydbpass",
      DB: "mydb"
      }
      d.vagrant_vagrantfile = "./Vagrantfile.host"
  end
end
 
  
#Define container 2
config.vm.define "rails" do |v|
  v.vm.provider "docker" do |d|
    d.image = "library/rails"
    d.ports = ["3000:3000 "]
    d.link("postgres:postgres")
    d.cmd = ["bundle install && bundle exec passenger -p 3000"]
    d.vagrant_vagrantfile = "./Vagrantfile.host"
    end
end



end 

